# Generated by Django 4.0.8 on 2022-12-28 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultall',
            name='menu',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='resultall',
            name='restaurant',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
